### PR TITLE
Fix #327

### LINKED ISSUE #327: "type" parameter to prompt defaults to int, but docs say str
[terminal.py:111](https://github.com/tomerfiliba/plumbum/blob/df7ab6a543a0f7046a01240259669ed5b971a17c/plumbum/cli/terminal.py#L111):

```python
def prompt(question, type = int, default = NotImplemented, validator = lambda val: True):
```

[terminal.py:117](https://github.com/tomerfiliba/plumbum/blob/df7ab6a543a0f7046a01240259669ed5b971a17c/plumbum/cli/terminal.py#L117):

```
    :param type: The type of the answer, defaults to str
```

One of these should change, though I'm not sure which one. My guess would be make the default `str`.

### PR DESCRIPTION
**Pull request by AndydeCleyre**
Fix #327 in one of two obvious ways. prompt type defaults to str, to match docs.

### CODE REVIEW

**Comment by henryiii** [comment]
Can you add a note to the changelog, too, since this could possibly change code for someone who depends on the default parameter? Otherwise I think this is the correct way to change it.

**Comment by AndydeCleyre** [comment]
Let me know if it's a problem that my editor murdered a bunch of trailing spaces in the changelog.

**Comment by henryiii** [comment]
Trailing spaces deserve to be murdered :)

**Comment by henryiii** [comment]
Thanks!

**Comment by AndydeCleyre** [comment]
Thank you, this continues to be an amazing project.

**Pull request merged**
