### PR TITLE
Fix missing non-zero return code from TEE'd pipe

### LINKED ISSUE #660: TEE return code for pipeline is wrong when non-last command fails
Based on #145 
```py
from plumbum.cmd import yes, head
from plumbum import TEE, RETCODE

chain = yes['-x'] | head
print(chain & RETCODE)  # prints 1
with chain.bgrun(retcode=None) as p:
    print(p.run()[0])   # prints 1
print((chain & TEE(retcode=None))[0])  # prints 0
```

### PR DESCRIPTION
**Pull request by vient**
I checked that modified test is failing, and fix in this branch makes it green.

Fixes #660

### CODE REVIEW

**Comment by vient** [comment]
Wat

Looks like a bug in CI, I've run nox locally, it was successful.

**Comment by henryiii** [comment]
Yeah, I think it is. Will look at it when on a computer.

**Comment by vient** [comment]
Btw, nox is great. I did not know what it is, installed it, and it just worked from the first try, and ran all tests? Super cool

**Comment by henryiii** [comment]
See https://learn.scientific-python.org/development/guides/tasks/ - I love it. :)

I see what's wrong - we've pinned an old pylint, and it doesn't support Python 3.12, which is what the default is now. I'm fixing that in a separate PR.

**Pull request merged**
