### PR TITLE
make ShellSession thread-safe when using .run()

### PR DESCRIPTION
**Pull request by koreno**
(Not sure if there's some philosophy against dealing with concurrency in plumbum?...)

### CODE REVIEW

**Comment by tomerfiliba** [comment]
it looks alright to me, but maybe it's better to ask @henryiii since i haven't touched it in years

**Comment by koreno** [comment]
> it looks alright to me, but maybe it's better to ask @henryiii since i haven't touched it in years

Woh! didn't actually expect you to respond... :smile:

**Comment by henryiii** [comment]
@tomerfiliba 

Wow, hi! I have some questions for you:

* Could you change the docs link from `plumbum.readthedocs.org` to `plumbum.readthedocs.io` on the GitHub page link, top right? I don't have permissions to change that link.
* Could you either give me permissions on the readthedocs build or fix it? It's been dead for about a year.

Glad to see you around. :)

**Review by henryiii — APPROVED** [review]

**Comment by tomerfiliba** [comment]
done
-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com     <http://www.facebook.com/tomerfiliba>
<http://il.linkedin.com/in/tomerfiliba>

**Comment by henryiii** [comment]
What about the readthedocs build? My username is the same on readthedocs if you want me to investigate.

Screen Shot 2020-09-10 at 3 40 21 PM

**Comment by tomerfiliba** [comment]
i added you as a maintainer to readthedocs

**Comment by henryiii** [comment]
@tomerfiliba Thanks! Found the problem. The GitHub URL was http instead of https; I guess they turned that off a year and nine months ago. Docs are current again. :)

**Pull request merged**
