### PR TITLE
Add timeouts into the ExecutionModifiers

### PR DESCRIPTION
**Pull request by fahhem**
This pipes run_proc's timeout argument farther up the stack.

I'm hoping the tests will catch if this hits any parts that don't accept timeout and I'll add it to those as well.

### CODE REVIEW

**Comment by fahhem** [comment]
Looks like the only failure in travis is due to Python nightly changing the string representation of ints. Should I fix that in this PR or a separate one?

**Comment by henryiii** [comment]
One PR is okay with me.
Henry

**Comment by fahhem** [comment]
Okay, the latest push should have passing tests

**Comment by henryiii** [comment]
Okay, I’ll look at it when I get off work.
Thanks!
Henry

**Pull request merged**
