### PR TITLE
paths: make subscription work for composing paths

### PR DESCRIPTION
**Pull request by koreno**

### CODE REVIEW

**Comment by koreno** [comment]
This is ready for you @henryiii, let me know what you think

**Comment by koreno** [comment]
@henryiii - what do you say, can we merge this?
and what's the criteria for releasing a new version?

**Comment by henryiii** [comment]
Sorry for the delay. I wasn't completely sure about this, I would like to make a paths behave as close to pathlib as possible,  having a many ways to do something can be confusing  and adds extra maintenance.

**Comment by henryiii** [comment]
I don't think it's necessarily bad, but those were my concerns.

**Comment by koreno** [comment]
> Sorry for the delay. I wasn't completely sure about this, I would like to make a paths behave as close to pathlib as possible, having a many ways to do something can be confusing and adds extra maintenance.

I guess it takes a "merge" to get your attention... :smile: 
I hear your concern, I just find the original syntax extremely inconvenient and not useful. as for pathlib - the fact it doesn't inherit from str makes it pretty inconvenient when used with other functions... but its also good since it means that subscription isn't conflicting with some other behavior (Afaik).

**Pull request merged**
