### PR TITLE
Scrap redundant encoding

### PR DESCRIPTION
**Pull request by koreno**

### CODE REVIEW

**Comment by henryiii** [comment]
Changed `self.encoding` to `self.custom_encoding` (edited it online and messed up the description)

**Comment by henryiii** [comment]
If travis builds, I'm good with the changes.

**Comment by henryiii** [comment]
Don't know what's wrong with travis, I'm going to go ahead and merge then fix if needed.

**Comment by koreno** [comment]
Thanks!

**Pull request merged**
