### PR TITLE
Add localization functions and russian localization

### LINKED ISSUE #335: I18N of cli.Application
It would be nice to have `--help` and usage messages localized, maybe using GNU gettext?

### PR DESCRIPTION
**Pull request by ASMfreaK**
This PR fixes #335 - It adds gettext localization to all strings that are used in Application output.
Also as a test I've written russian localization. Any other language can be easily added. 
This should be tested on py2.x and on Windows.

### CODE REVIEW

**Comment by henryiii** [comment]
This looks great. I'll try to get it in in a day or two. Thanks!

**Comment by henryiii** [comment]
Would you mind changing the `%` formatting into `{name}` formatting? That would be more consistent than using both styles, and would be easier for translators to use (for example, if they need to reorder a pair of messages). The fact that Plumbum currently mixes both styles is a historical relic.

**Comment by ASMfreaK** [comment]
I like braces formatting, too. Ok.

**Comment by henryiii** [comment]
LGTM.

**Comment by henryiii** [comment]
Thanks!!!

**Comment by ASMfreaK** [comment]
Yay~

**Pull request merged**
