### PR TITLE
Issue#219 - Fix for invalid stat arg on FreeBSD

### PR DESCRIPTION
**Pull request by astraw38**

### CODE REVIEW

**Comment by henryiii** [comment]
What about the almost matching lines directly above it, for `_path_getuid`, `_path_getgid`?

**Comment by henryiii** [comment]
Looks good to me. I'll leave it to @tomerfiliba for the final check.

PS, do you have direct access to a FreeBSD system? I'm curious as to how the default terminal works with `plumbum.colors`.

**Comment by tomerfiliba** [comment]
thanks

**Comment by astraw38** [comment]
@henryiii 

Only SSH access unfortunately.

**Comment by henryiii** [comment]
@astraw38 Okay, thanks for checking. Thanks for the patch, too!

**Pull request merged**
