### PR TITLE
cli: improved 'Set' validator supports csv and non-string types

### PR DESCRIPTION
**Pull request by koreno**

### CODE REVIEW

**Comment by jjlorenzo** [comment]
I get this error if I use master, I think is related to this change
```
Usage:
    tlawr-to-boot [SWITCHES] name

Traceback (most recent call last):
  File "/Users/jjlorenzo/Desktop/hackintosh/tlawr/.venv/src/plumbum/plumbum/cli/application.py", line 553, in run
    ordered, tailargs = inst._validate_args(swfuncs, tailargs)
  File "/Users/jjlorenzo/Desktop/hackintosh/tlawr/.venv/src/plumbum/plumbum/cli/application.py", line 432, in _validate_args
    raise ShowHelp()
plumbum.cli.application.ShowHelp

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jjlorenzo/Desktop/hackintosh/tlawr/.venv/bin/tlawr-to-boot", line 11, in <module>
    load_entry_point('tlawr', 'console_scripts', 'tlawr-to-boot')()
  File "/Users/jjlorenzo/Desktop/hackintosh/tlawr/.venv/src/plumbum/plumbum/cli/application.py", line 555, in run
    inst.help()
  File "/Users/jjlorenzo/Desktop/hackintosh/tlawr/.venv/src/plumbum/plumbum/cli/application.py", line 865, in help
    len(prefix) for si, prefix, color in switchs(by_groups, False)) + 4
  File "/Users/jjlorenzo/Desktop/hackintosh/tlawr/.venv/src/plumbum/plumbum/cli/application.py", line 865, in <genexpr>
    len(prefix) for si, prefix, color in switchs(by_groups, False)) + 4
  File "/Users/jjlorenzo/Desktop/hackintosh/tlawr/.venv/src/plumbum/plumbum/cli/application.py", line 853, in switchs
    typename = str(si.argtype)
  File "/Users/jjlorenzo/Desktop/hackintosh/tlawr/.venv/src/plumbum/plumbum/cli/switches.py", line 471, in __repr__
    v if isinstance(v, str) else v.__name__ for v in self.values.values()))
AttributeError: 'tuple' object has no attribute 'values'
```

with something as simpler as 
```
echoes = cli.SwitchAttr("echo", cli.Set("registry"), list=True, help="echoes")
```

**Comment by henryiii** [comment]
This is a blocker for #445. We need a test for this plus the new behavior (this was added without tests! :( )

**Comment by henryiii** [comment]
(PS: It would be better to open an issue then refer to this PR, rather than comment on an old PR)

**Comment by koreno** [comment]
you're right, my bad, will fix promptly

- Ofer

**Pull request merged**
