### PR TITLE
Ensure fair error attribution of pipelined return codes

### LINKED ISSUE #241: ProcessExecutionError is misleading when piped commands fail
Relates to #145 

```
Type "help", "copyright", "credits" or "license" for more information.
>>> from plumbum.cmd import cat, head
>>> from plumbum import FG
>>> (cat['/dev/urndom'] | head['-c', '10']) & FG()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nail/home/josnyder/consul-backups/env/local/lib/python2.7/site-packages/plumbum/commands/modifiers.py", line 143, in __rand__
    cmd(retcode = self.retcode, stdin = None, stdout = None, stderr = None)
  File "/nail/home/josnyder/consul-backups/env/local/lib/python2.7/site-packages/plumbum/commands/base.py", line 89, in __call__
    return self.run(args, **kwargs)[1]
  File "/nail/home/josnyder/consul-backups/env/local/lib/python2.7/site-packages/plumbum/commands/base.py", line 219, in run
    return p.run()
  File "/nail/home/josnyder/consul-backups/env/local/lib/python2.7/site-packages/plumbum/commands/base.py", line 181, in runner
    return run_proc(p, retcode, timeout)
  File "/nail/home/josnyder/consul-backups/env/local/lib/python2.7/site-packages/plumbum/commands/processes.py", line 217, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/nail/home/josnyder/consul-backups/env/local/lib/python2.7/site-packages/plumbum/commands/processes.py", line 34, in _check_process
    stdout, stderr)
plumbum.commands.processes.ProcessExecutionError: Command line: ['/usr/bin/head', '-c', '10']
Exit code: 1
```

In this example, the process which failed is the cat process.  The exception message is misleading, because it implies that the head process failed.

### PR DESCRIPTION
**Pull request by hashbrowncipher**
Fixes #241 by making the (new) verify method on command objects responsible for determining whether to raise an exception.

### CODE REVIEW

**Comment by hashbrowncipher** [comment]
Worth noting is that my penultimate commit modifies a test that would otherwise fail due to a behavioral change.  I believe that fixing the test, as it was originally written, would require implementing the TODO I left on line 303 of base.py.

**Comment by henryiii** [comment]
This looks good to me. I'll let @tomerfiliba or @koreno check it over, then I'm okay to merge. I will need this merged before I submit my fix for #240.

**Comment by henryiii** [comment]
I'll go ahead and merge this, so I can add a few help strings and submit my patch.

**Comment by henryiii** [comment]
We'll need to fix that test before releasing 1.6.1, I believe, as only requiring the final error code seems more intuitive (and it's the way it used to work). I'm looking at that, feel free to do so too.

**Comment by henryiii** [comment]
I believe the issue really is that plumbum follows a non-standard return code policy. That is,
`false | true` has a return code of 0 in bash. Plumbum uses `or` to combine return code, making 0 special regardless of your requested return code.

I've set it so that 0 is expected for everything except the last command, which fixes the test that failed because it is the way plumbum has always worked. It just didn't attribute the non-zero command because it was a simple or, rather than the method of this patch.

If we can attach an expected return code to processes, that would be the ideal way to allow custom return code management. That should not be hard now that each command is properly tested.

**Comment by henryiii** [comment]
Correction: I've now set it so that the old behavior is exactly restored (though with the correct attribution now in place). We can discuss changing it for 1.7.0, but probably not for v1.6.1. I think adding a way to set each command's return code is probably the way to go from here, though. Like:
```python
ls['-a'].set_retcode([0,1]) & FG
```
Where `.set_retcode` sets a property and returns `self`. Then, if that property exists / is not some special value, that is used for verify instead. A little verbose, but don't see another better way ATM.

**Comment by hashbrowncipher** [comment]
That's gorgeous, thanks @henryiii.

I think your solution involving set_retcode is a good one.  I would recommend normative names like 'expect_code' or 'should_return' or (if you like brevity) 'returns'.

**Pull request merged**
