### PR TITLE
added TypedEnv, for easy parsing of env-vars

### PR DESCRIPTION
**Pull request by koreno**

### CODE REVIEW

**Comment by henryiii** [comment]
Python 2 support, please. We haven't dropped Python 2.6 yet, though that's planned for 1.7. A future 2.0 could drop Python 2 support. Since Plumbum is a scripting helper, it should work with any system Python, and CentOS 7 still is on 2.6, macOS is on 2.7 (until it drops all scripting languages in a release or two, anyway).

**Comment by henryiii** [comment]
I *think* you could just move the `**` test into a test marked with Python3 only.

**Comment by henryiii** [comment]
Would you be interested in writing docs/changelog for this and the other additions you've just made? If not I will, but it would be slightly delayed, probably.

**Comment by koreno** [comment]
> Would you be interested in writing docs/changelog for this and the other additions you've just made? If not I will, but it would be slightly delayed, probably.

I'll try to do it, unless you get to it before me...

**Comment by koreno** [comment]
@henryiii - should I merge this?

**Comment by henryiii** [comment]
It’s okay, I can. Have been busy so ping me as needed (like you did).

**Pull request merged**
